#!/bin/bash

#run multiple python sessions at once

python single_SSM_run.py 2 &
python single_SSM_run.py 2 &
python single_SSM_run.py 2 &
python single_SSM_run.py 2 &
python single_SSM_run.py 2 &
python single_SSM_run.py 2 &
python single_SSM_run.py 2 &
python single_SSM_run.py 2
